name: linting

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 6.0.2

      - name: Install deps and build (with cache)
        run: pnpm install valibot fastify ajv

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: pnpm build

